workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "Main.swift"
        XCODE_SCHEME: "App"
    scripts:
      - name: Build
        script: |
          echo "Compilazione in corso..."
    artifacts:
      - build/ios
    publishing:
      email:
        recipients:
          - ivan.barby@icloud.com